image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [214.66078,   1.0922 , 315.6348 ,
           0.     , 290.57542, 264.9878 ,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.050541, -0.179978, 0.638839, -0.259941]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [214.66078,   1.0922 , 315.6348 ,   0.     ,
           0.     , 290.57542, 264.9878 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
