slam_toolbox:
  ros__parameters:
    # Basic frames
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    scan_topic: /scan
    
    # Laser parameters (match your RPLiDAR specs)
    minimum_laser_range: 0.1
    maximum_laser_range: 12.0
    
    # Performance tuning to reduce message dropping
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 12.0
    tf_buffer_duration: 30.0
    
    # Reduce drift with tighter constraints
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_response_coarse: 0.35
    loop_match_maximum_response_coarse: 0.45
    
    # Motion model tuning for dog movement
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    
    # Solver settings
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG